<?php
/**
 * @file
 * onboard_types.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function onboard_types_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'uid' => 1,
  'title' => 'About Local Government',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '8a1041f4-cae0-420e-bbde-6d8054afe3b2',
  'type' => 'page',
  'language' => 'und',
  'created' => 1386452459,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '18aeee0d-abfc-4463-bbeb-f1762c6ff923',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Gummi bears marshmallow dessert tootsie roll tootsie roll croissant tiramisu. Sesame snaps pie tiramisu muffin bear claw. Chocolate bar biscuit tart lemon drops topping candy canes. Pie sweet topping marzipan cupcake pie. Marshmallow cheesecake candy. Cupcake halvah muffin jelly beans powder jelly beans candy. Chocolate chocolate bar jelly beans apple pie apple pie fruitcake.

Tootsie roll cake wafer soufflé carrot cake macaroon. Wafer soufflé gummi bears cheesecake bonbon. Topping sweet roll gingerbread jelly-o cupcake. Sugar plum dessert marshmallow lollipop marshmallow apple pie sweet biscuit lemon drops. Soufflé marshmallow tiramisu sweet. Bear claw applicake marshmallow unerdwear.com caramels cheesecake cupcake.

Jelly beans applicake bear claw candy canes tootsie roll marzipan danish cake. Topping marzipan toffee icing macaroon jelly-o oat cake. Soufflé marzipan halvah halvah oat cake gingerbread gingerbread tootsie roll. Muffin danish pie croissant toffee pudding dragée. Apple pie jujubes jujubes. Liquorice cookie wafer. Topping sesame snaps halvah. Oat cake sweet sweet danish cake carrot cake soufflé chupa chups bonbon.

Topping topping brownie jelly-o caramels. Jelly-o chocolate bar applicake danish tootsie roll pie. Marzipan chupa chups unerdwear.com applicake chocolate cake pie tootsie roll lemon drops muffin. Jelly topping oat cake fruitcake bear claw bear claw marshmallow pie tiramisu. Gingerbread tootsie roll croissant. Fruitcake lollipop cheesecake dragée topping dragée unerdwear.com cookie. Icing cupcake sweet bear claw biscuit applicake. Donut candy canes cheesecake pastry candy sweet. Toffee cotton candy dessert jujubes sugar plum cupcake.

Cupcake soufflé apple pie marzipan. Gummies donut tart bear claw. Chupa chups gummies sweet cupcake tootsie roll tootsie roll. Candy caramels powder gummi bears apple pie. Gingerbread icing pudding danish oat cake. Toffee pastry bear claw. Icing bonbon lemon drops donut marzipan sesame snaps. Apple pie chocolate tiramisu cheesecake sweet roll soufflé fruitcake marshmallow donut.',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>Gummi bears marshmallow dessert tootsie roll tootsie roll croissant tiramisu. Sesame snaps pie tiramisu muffin bear claw. Chocolate bar biscuit tart lemon drops topping candy canes. Pie sweet topping marzipan cupcake pie. Marshmallow cheesecake candy. Cupcake halvah muffin jelly beans powder jelly beans candy. Chocolate chocolate bar jelly beans apple pie apple pie fruitcake.</p>
<p>Tootsie roll cake wafer soufflé carrot cake macaroon. Wafer soufflé gummi bears cheesecake bonbon. Topping sweet roll gingerbread jelly-o cupcake. Sugar plum dessert marshmallow lollipop marshmallow apple pie sweet biscuit lemon drops. Soufflé marshmallow tiramisu sweet. Bear claw applicake marshmallow unerdwear.com caramels cheesecake cupcake.</p>
<p>Jelly beans applicake bear claw candy canes tootsie roll marzipan danish cake. Topping marzipan toffee icing macaroon jelly-o oat cake. Soufflé marzipan halvah halvah oat cake gingerbread gingerbread tootsie roll. Muffin danish pie croissant toffee pudding dragée. Apple pie jujubes jujubes. Liquorice cookie wafer. Topping sesame snaps halvah. Oat cake sweet sweet danish cake carrot cake soufflé chupa chups bonbon.</p>
<p>Topping topping brownie jelly-o caramels. Jelly-o chocolate bar applicake danish tootsie roll pie. Marzipan chupa chups unerdwear.com applicake chocolate cake pie tootsie roll lemon drops muffin. Jelly topping oat cake fruitcake bear claw bear claw marshmallow pie tiramisu. Gingerbread tootsie roll croissant. Fruitcake lollipop cheesecake dragée topping dragée unerdwear.com cookie. Icing cupcake sweet bear claw biscuit applicake. Donut candy canes cheesecake pastry candy sweet. Toffee cotton candy dessert jujubes sugar plum cupcake.</p>
<p>Cupcake soufflé apple pie marzipan. Gummies donut tart bear claw. Chupa chups gummies sweet cupcake tootsie roll tootsie roll. Candy caramels powder gummi bears apple pie. Gingerbread icing pudding danish oat cake. Toffee pastry bear claw. Icing bonbon lemon drops donut marzipan sesame snaps. Apple pie chocolate tiramisu cheesecake sweet roll soufflé fruitcake marshmallow donut.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2013-12-07 16:40:59 -0500',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Feedback',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'c59a0b83-4f44-4d1a-bc02-b8ed8898a05d',
  'type' => 'webform',
  'language' => 'und',
  'created' => 1387302994,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'a49de065-9828-45ea-aec5-4ccd0b4bf8bf',
  'revision_uid' => 7,
  'field_body' => array(
    'und' => array(
      0 => array(
        'value' => 'On Board is designed to provide you with information about boards and commissions and give you a clear pathway to getting involved. Have we accomplished our goals? How might we improve? Please complete the form below in as much detail as possible. ',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>On Board is designed to provide you with information about boards and commissions and give you a clear pathway to getting involved. Have we accomplished our goals? How might we improve? Please complete the form below in as much detail as possible.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'webform' => array(
    'nid' => 57,
    'confirmation' => '',
    'confirmation_format' => NULL,
    'redirect_url' => '<confirmation>',
    'status' => 1,
    'block' => 0,
    'allow_draft' => 0,
    'auto_save' => 0,
    'submit_notice' => 1,
    'submit_text' => '',
    'submit_limit' => -1,
    'submit_interval' => -1,
    'total_submit_limit' => -1,
    'total_submit_interval' => -1,
    'progressbar_bar' => 1,
    'progressbar_page_number' => 0,
    'progressbar_percent' => 0,
    'progressbar_pagebreak_labels' => 1,
    'progressbar_include_confirmation' => 1,
    'progressbar_label_first' => 'Start',
    'progressbar_label_confirmation' => 'Complete',
    'record_exists' => TRUE,
    'roles' => array(
      0 => 1,
      1 => 2,
    ),
    'emails' => array(),
    'components' => array(
      1 => array(
        'nid' => 57,
        'cid' => 1,
        'pid' => 0,
        'form_key' => 'name',
        'name' => 'Your name',
        'type' => 'textfield',
        'value' => '',
        'extra' => array(
          'title_display' => 'before',
          'private' => 0,
          'wrapper_classes' => '',
          'css_classes' => '',
          'width' => '',
          'maxlength' => '',
          'field_prefix' => '',
          'field_suffix' => '',
          'disabled' => 0,
          'unique' => 0,
          'description' => '',
          'placeholder' => '',
          'attributes' => array(),
          'analysis' => FALSE,
        ),
        'required' => 0,
        'weight' => 0,
        'page_num' => 1,
      ),
      2 => array(
        'nid' => 57,
        'cid' => 2,
        'pid' => 0,
        'form_key' => 'mail',
        'name' => 'Your email',
        'type' => 'email',
        'value' => '[current-user:mail]',
        'extra' => array(
          'title_display' => 'before',
          'private' => 0,
          'wrapper_classes' => '',
          'css_classes' => '',
          'width' => '',
          'unique' => 0,
          'disabled' => 0,
          'description' => '',
          'placeholder' => '',
          'attributes' => array(),
          'analysis' => FALSE,
        ),
        'required' => 0,
        'weight' => 1,
        'page_num' => 1,
      ),
      4 => array(
        'nid' => 57,
        'cid' => 4,
        'pid' => 0,
        'form_key' => 'your_phone_number',
        'name' => 'Your phone number',
        'type' => 'textfield',
        'value' => '',
        'extra' => array(
          'title_display' => 'before',
          'private' => 0,
          'wrapper_classes' => '',
          'css_classes' => '',
          'width' => '',
          'maxlength' => '',
          'field_prefix' => '',
          'field_suffix' => '',
          'disabled' => 0,
          'unique' => 0,
          'description' => '',
          'placeholder' => '',
          'attributes' => array(),
          'analysis' => FALSE,
        ),
        'required' => 0,
        'weight' => 2,
        'page_num' => 1,
      ),
      3 => array(
        'nid' => 57,
        'cid' => 3,
        'pid' => 0,
        'form_key' => 'feedback',
        'name' => 'Your Feedback',
        'type' => 'textarea',
        'value' => '',
        'extra' => array(
          'title_display' => 'before',
          'private' => 0,
          'wrapper_classes' => '',
          'css_classes' => '',
          'cols' => '',
          'rows' => '',
          'resizable' => 1,
          'disabled' => 0,
          'description' => '',
          'placeholder' => '',
          'attributes' => array(),
          'analysis' => FALSE,
        ),
        'required' => 1,
        'weight' => 3,
        'page_num' => 1,
      ),
    ),
    'conditionals' => array(),
  ),
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2013-12-17 12:56:34 -0500',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Get help',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 1,
  'sticky' => 0,
  'vuuid' => '48e0a76e-03be-4e1e-ab60-ff7923d6fdc6',
  'type' => 'webform',
  'language' => 'und',
  'created' => 1387492568,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'd9d31c1a-6518-4b8f-bb6b-897e6f693a28',
  'revision_uid' => 7,
  'field_body' => array(
    'und' => array(
      0 => array(
        'value' => 'Need help? Call Emily Thompson at the Michigan Suburbs Alliance at (313) 444-4830 or complete the form below in as much detail as possible. ',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>Need help? Call Emily Thompson at the Michigan Suburbs Alliance at (313) 444-4830 or complete the form below in as much detail as possible.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'webform' => array(
    'nid' => 65,
    'confirmation' => '',
    'confirmation_format' => NULL,
    'redirect_url' => '<confirmation>',
    'status' => 1,
    'block' => 0,
    'allow_draft' => 0,
    'auto_save' => 0,
    'submit_notice' => 1,
    'submit_text' => '',
    'submit_limit' => -1,
    'submit_interval' => -1,
    'total_submit_limit' => -1,
    'total_submit_interval' => -1,
    'progressbar_bar' => 1,
    'progressbar_page_number' => 0,
    'progressbar_percent' => 0,
    'progressbar_pagebreak_labels' => 1,
    'progressbar_include_confirmation' => 1,
    'progressbar_label_first' => 'Start',
    'progressbar_label_confirmation' => 'Complete',
    'record_exists' => TRUE,
    'roles' => array(
      0 => 1,
      1 => 2,
    ),
    'emails' => array(),
    'components' => array(
      1 => array(
        'nid' => 65,
        'cid' => 1,
        'pid' => 0,
        'form_key' => 'name',
        'name' => 'Name',
        'type' => 'textfield',
        'value' => '[current-user:name]',
        'extra' => array(
          'title_display' => 'before',
          'private' => 0,
          'wrapper_classes' => '',
          'css_classes' => '',
          'width' => '',
          'maxlength' => '',
          'field_prefix' => '',
          'field_suffix' => '',
          'disabled' => 0,
          'unique' => 0,
          'description' => '',
          'placeholder' => '',
          'attributes' => array(),
          'analysis' => FALSE,
        ),
        'required' => 1,
        'weight' => 0,
        'page_num' => 1,
      ),
      2 => array(
        'nid' => 65,
        'cid' => 2,
        'pid' => 0,
        'form_key' => 'describe_what_you_need_help_with',
        'name' => 'Describe what you need help with or give us your feedback',
        'type' => 'textarea',
        'value' => '',
        'extra' => array(
          'title_display' => 'before',
          'private' => 0,
          'wrapper_classes' => '',
          'css_classes' => '',
          'cols' => '',
          'rows' => '',
          'resizable' => 1,
          'disabled' => 0,
          'description' => '',
          'placeholder' => '',
          'attributes' => array(),
          'analysis' => FALSE,
        ),
        'required' => 1,
        'weight' => 1,
        'page_num' => 1,
      ),
    ),
    'conditionals' => array(),
  ),
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2013-12-19 17:36:08 -0500',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'About Us',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '10982589-2c74-4a79-9781-c44aeb8933c3',
  'type' => 'page',
  'language' => 'und',
  'created' => 1386452439,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'db6dd32f-330c-40b2-98fb-c15be223dc56',
  'revision_uid' => 7,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'On Board is a project of the <a href="http://www.michigansuburbsalliance.org/">Michigan Suburbs Alliance</a>, a 501(c)3 nonprofit organization, which works to foster and support cooperative approaches to the challenges facing Michigan’s metropolitan areas. Through innovative initiatives we organize, serve and advocate for metro Detroit’s cities in order to help them be vibrant, healthy and beautiful communities. We also strive to actively engage a diverse group of people in municipal and regional affairs. 

<strong>On Board<strong>

In late 2012, the City of Detroit and 22 of its suburban neighbors asked us to research Millennial participating in local government. These communities believe young people are excited about opportunities for development and growth in metro Detroit, but assumed these residents were underrepresented and therefore limited in their ability to affect change.

With this in mind, we looked at Millennial representation on boards and commissions in 23 cities across metro Detroit, and at how cities share information and recruit applicants. Our research shows young people (age 18-35) are underrepresented: they account for 22.5% of the population in metro Detroit and 29.0% of registered voters, but only 6.0% of board and commission members. What’s more, few communities provide comprehensive information about their boards and commissions online. 

Armed with this new information, we applied for a grant from the <a href="http://www.knightfoundation.org/">James S. and John L. Knight Foundation</a> to bring information about local boards and commissions, and the application and appointment process in particular, online. <a href="http://opengov.newschallenge.org/open/open-government/submission/really-simple-service-rss-bringing-opportunity-online/">(View our proposal here.)</a> Last summer, we were awarded a $50,000 Prototype Fund grant and since then we’ve been hard at work to build and bring you On Board! 

Interested in learning more about or participating in On Board? Contact Emily Thompson at the Michigan Suburbs Alliance at (313) 444-4830 or emily@suburbsalliance.org. ',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>On Board is a project of the <a href="http://www.michigansuburbsalliance.org/">Michigan Suburbs Alliance</a>, a 501(c)3 nonprofit organization, which works to foster and support cooperative approaches to the challenges facing Michigan’s metropolitan areas. Through innovative initiatives we organize, serve and advocate for metro Detroit’s cities in order to help them be vibrant, healthy and beautiful communities. We also strive to actively engage a diverse group of people in municipal and regional affairs. </p>
<p><strong>On Board<strong></strong></strong></p>
<p>In late 2012, the City of Detroit and 22 of its suburban neighbors asked us to research Millennial participating in local government. These communities believe young people are excited about opportunities for development and growth in metro Detroit, but assumed these residents were underrepresented and therefore limited in their ability to affect change.</p>
<p>With this in mind, we looked at Millennial representation on boards and commissions in 23 cities across metro Detroit, and at how cities share information and recruit applicants. Our research shows young people (age 18-35) are underrepresented: they account for 22.5% of the population in metro Detroit and 29.0% of registered voters, but only 6.0% of board and commission members. What’s more, few communities provide comprehensive information about their boards and commissions online. </p>
<p>Armed with this new information, we applied for a grant from the <a href="http://www.knightfoundation.org/">James S. and John L. Knight Foundation</a> to bring information about local boards and commissions, and the application and appointment process in particular, online. <a href="http://opengov.newschallenge.org/open/open-government/submission/really-simple-service-rss-bringing-opportunity-online/">(View our proposal here.)</a> Last summer, we were awarded a $50,000 Prototype Fund grant and since then we’ve been hard at work to build and bring you On Board! </p>
<p>Interested in learning more about or participating in On Board? Contact Emily Thompson at the Michigan Suburbs Alliance at (313) 444-4830 or <a href="mailto:emily@suburbsalliance.org">emily@suburbsalliance.org</a>.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2013-12-07 16:40:39 -0500',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Welcome',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'afc0b544-ed5d-4600-b1e1-b64f10e93937',
  'type' => 'page',
  'language' => 'und',
  'created' => 1387475982,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'f13cc27a-1823-4ea0-850a-6d95d055742b',
  'revision_uid' => 7,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<strong> Interested in joining the thousands of volunteers who serve on a local board or commission in metro Detroit?<strong>

Local governments rely on local appointed bodies for advice, ideas, and assistance in achieving public goals. Unfortunately many residents are unaware of or don’t understand how to engage with these bodies. We hope to change this with On Board, which is designed to help local governments keep track of and share information with residents, and give residents a clear pathway to getting involved.

<strong> Get started by checking out the boards and commissions in your community:<strong>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p><strong> Interested in joining the thousands of volunteers who serve on a local board or commission in metro Detroit?<strong></strong></strong></p>
<p>Local governments rely on local appointed bodies for advice, ideas, and assistance in achieving public goals. Unfortunately many residents are unaware of or don’t understand how to engage with these bodies. We hope to change this with On Board, which is designed to help local governments keep track of and share information with residents, and give residents a clear pathway to getting involved.</p>
<p><strong> Get started by checking out the boards and commissions in your community:<strong></strong></strong></p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2013-12-19 12:59:42 -0500',
);
  return $nodes;
}
